<?php

// Register snippets
$kirby->set('snippet', 'contact',                    __DIR__.DS.'..'.DS.'snippets'.DS.'contact.php');
$kirby->set('snippet', 'footer',                     __DIR__.DS.'..'.DS.'snippets'.DS.'footer.php');
$kirby->set('snippet', 'header',                     __DIR__.DS.'..'.DS.'snippets'.DS.'header.php');
$kirby->set('snippet', 'header.background.style',    __DIR__.DS.'..'.DS.'snippets'.DS.'header.background.style.php');
$kirby->set('snippet', 'header.menus',               __DIR__.DS.'..'.DS.'snippets'.DS.'header.menus.php');
$kirby->set('snippet', 'list.category',              __DIR__.DS.'..'.DS.'snippets'.DS.'list.category.php');
$kirby->set('snippet', 'list.featured',              __DIR__.DS.'..'.DS.'snippets'.DS.'list.featured.php');
$kirby->set('snippet', 'list.product',               __DIR__.DS.'..'.DS.'snippets'.DS.'list.product.php');
$kirby->set('snippet', 'list.related',               __DIR__.DS.'..'.DS.'snippets'.DS.'list.related.php');
$kirby->set('snippet', 'login',                      __DIR__.DS.'..'.DS.'snippets'.DS.'login.php');
$kirby->set('snippet', 'logo',                       __DIR__.DS.'..'.DS.'snippets'.DS.'logo.php');
$kirby->set('snippet', 'mail.order.notify',          __DIR__.DS.'..'.DS.'snippets'.DS.'mail.order.notify.php');
$kirby->set('snippet', 'mail.order.notify.status',   __DIR__.DS.'..'.DS.'snippets'.DS.'mail.order.notify.status.php');
$kirby->set('snippet', 'mail.order.update.error',    __DIR__.DS.'..'.DS.'snippets'.DS.'mail.order.update.error.php');
$kirby->set('snippet', 'mail.order.tamper',          __DIR__.DS.'..'.DS.'snippets'.DS.'mail.order.tamper.php');
$kirby->set('snippet', 'menu.brands',                __DIR__.DS.'..'.DS.'snippets'.DS.'menu.brands.php');
$kirby->set('snippet', 'menu.breadcrumb',            __DIR__.DS.'..'.DS.'snippets'.DS.'menu.breadcrumb.php');
$kirby->set('snippet', 'menu.categories',            __DIR__.DS.'..'.DS.'snippets'.DS.'menu.categories.php');
$kirby->set('snippet', 'menu.primary',               __DIR__.DS.'..'.DS.'snippets'.DS.'menu.primary.php');
$kirby->set('snippet', 'menu.subpages',              __DIR__.DS.'..'.DS.'snippets'.DS.'menu.subpages.php');
$kirby->set('snippet', 'menu.tags',                  __DIR__.DS.'..'.DS.'snippets'.DS.'menu.tags.php');
$kirby->set('snippet', 'menu.user',                  __DIR__.DS.'..'.DS.'snippets'.DS.'menu.user.php');
$kirby->set('snippet', 'notifications',              __DIR__.DS.'..'.DS.'snippets'.DS.'notifications.php');
$kirby->set('snippet', 'order.callback',             __DIR__.DS.'..'.DS.'snippets'.DS.'order.callback.php');
$kirby->set('snippet', 'order.details',              __DIR__.DS.'..'.DS.'snippets'.DS.'order.details.php');
$kirby->set('snippet', 'order.pdf',                  __DIR__.DS.'..'.DS.'snippets'.DS.'order.pdf.php');
$kirby->set('snippet', 'search',                     __DIR__.DS.'..'.DS.'snippets'.DS.'search.php');
$kirby->set('snippet', 'sidebar',                    __DIR__.DS.'..'.DS.'snippets'.DS.'sidebar.php');
$kirby->set('snippet', 'slider',                     __DIR__.DS.'..'.DS.'snippets'.DS.'slider.php');
$kirby->set('snippet', 'slideshow.product',          __DIR__.DS.'..'.DS.'snippets'.DS.'slideshow.product.php');